import pandas as pd
import csv
from numpy import dstack, hstack, mean, std
from tensorflow.keras.utils import to_categorical
import numpy as np
from sklearn.model_selection import train_test_split

'''
data_filenames = [
    'Training_data\\0\\data_0_22_v7.csv', 'Training_data\\0\\data_0_22_2_v7.csv',
    'Training_data\\0\\data_0_121_s1_t1_1_v7.csv', 'Training_data\\0\\data_0_211_s1_t1_1_v7.csv',
    'Training_data\\0\\data_0_220_s1_t1_1_v7.csv', 'Training_data\\0\\data_0_221_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_011_021_v7.csv', 'Training_data\\1\\data_1_120_122_v7.csv',
    'Training_data\\1\\data_1_021_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_120_s1_t1_1_v7.csv', 'Training_data\\1\\data_1_122_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_021_s2_t1_1_v7.csv',
    'Training_data\\2\\data_2_22_v7.csv', 'Training_data\\2\\data_2_22_2_v7.csv',
    'Training_data\\2\\data_2_121_s1_t1_1_v7.csv', 'Training_data\\2\\data_2_211_s1_t1_1_v7.csv',
    'Training_data\\2\\data_2_220_s1_t1_1_v7.csv', 'Training_data\\2\\data_2_221_s1_t1_1_v7.csv',
    'Training_data\\2\\data_2_222_s1_t1_1_v7.csv',
    'Training_data\\3\\data_3_22_v7.csv', 'Training_data\\3\\data_3_22_2_v7.csv',
    'Training_data\\3\\data_3_121_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_121_s2_t1_1_v7.csv',
    'Training_data\\3\\data_3_220_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_220_s2_t1_1_v7.csv',
    'Training_data\\3\\data_3_221_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_221_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_221_v7.csv', 'Training_data\\4\\data_4_221_2_v7.csv',
    'Training_data\\4\\data_4_121_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_121_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_211_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_211_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_210_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_210_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_220_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_220_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_221_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_221_s2_t1_1_v7.csv',
    'Training_data\\5\\data_5_221_v7.csv', 'Training_data\\5\\data_5_221_2_v7.csv',
    'Training_data\\5\\data_5_121_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_121_s1_t2_1_v7.csv',
    'Training_data\\5\\data_5_220_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_220_s1_t2_1_v7.csv',
    'Training_data\\5\\data_5_221_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_221_s1_t2_1_v7.csv',
    'Training_data\\6\\data_6_121_v7.csv', 'Training_data\\6\\data_6_221_220_v7.csv',
    'Training_data\\6\\data_6_121_s1_t1_1_v7.csv', 'Training_data\\6\\data_6_221_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_v7.csv', 'Training_data\\7\\data_7_221_3_v7.csv', 'Training_data\\7\\data_7_221_2_v7.csv',
    'Training_data\\7\\data_7_121_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_121_s2_t1_1_v7.csv', 'Training_data\\7\\data_7_121_s3_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_s2_t1_1_v7.csv', 'Training_data\\7\\data_7_221_s3_t1_1_v7.csv',
    'Training_data\\8\\data_8_221_v7.csv', 'Training_data\\8\\data_8_221_3_v7.csv',
    'Training_data\\8\\data_8_121_s1_t1_1_v7.csv', 'Training_data\\8\\data_8_121_s1_t2_1_v7.csv',
    'Training_data\\8\\data_8_121_s1_t3_1_v7.csv', 'Training_data\\8\\data_8_220_s1_t1_1_v7.csv',
    'Training_data\\8\\data_8_220_s1_t2_1_v7.csv', 'Training_data\\8\\data_8_220_s1_t3_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t1_1_v7.csv', 'Training_data\\8\\data_8_221_s1_t2_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t3_1_v7.csv', 'Training_data\\8\\data_8_221_s1_t4_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t5_1_v7.csv', 'Training_data\\8\\data_8_121_s1_t4_1_v7.csv',
    'Training_data\\9\\data_9_120_v7.csv', 'Training_data\\9\\data_9_221_220_v7.csv',
    'Training_data\\9\\data_9_221_220_3_v7.csv',
    'Training_data\\9\\data_9_120_s1_t1_1_v7.csv', 'Training_data\\9\\data_9_121_s1_t1_1_v7.csv',
    'Training_data\\9\\data_9_220_s1_t1_1_v7.csv', 'Training_data\\9\\data_9_221_s1_t1_1_v7.csv',

    'Testing_data\\jundaWu\\data_0_jundaWu_v7.csv', 'Testing_data\\jundaWu\\data_1_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_2_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_3_jundaWu_v7.csv', 'Testing_data\\jundaWu\\data_4_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_5_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_6_jundaWu_v7.csv', 'Testing_data\\jundaWu\\data_7_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_8_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_9_jundaWu_v7.csv',
    'Testing_data\\xinyunXu\\data_0_XinyunXu_v7.csv', 'Testing_data\\xinyunXu\\data_1_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_2_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_3_XinyunXu_v7.csv', 'Testing_data\\xinyunXu\\data_4_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_5_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_6_XinyunXu_v7.csv', 'Testing_data\\xinyunXu\\data_7_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_8_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_9_XinyunXu_v7.csv',
    'Testing_data\\yuanhaoXie\\data_0_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_1_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_2_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_3_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_4_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_5_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_6_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_7_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_8_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_9_xie_3_v7.csv',
    'Testing_data\\zehangWu\\data_0_ZehangWu_v7.csv', 'Testing_data\\zehangWu\\data_1_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_2_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_3_ZehangWu_v7.csv', 'Testing_data\\zehangWu\\data_4_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_5_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_6_ZehangWu_v7.csv', 'Testing_data\\zehangWu\\data_7_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_8_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_9_ZehangWu_v7.csv',
    'Testing_data\\Liang\\data_0_Liang_v7.csv', 'Testing_data\\Liang\\data_1_Liang_v7.csv',
    'Testing_data\\Liang\\data_2_Liang_v7.csv',
    'Testing_data\\Liang\\data_3_Liang_v7.csv', 'Testing_data\\Liang\\data_4_Liang_v7.csv',
    'Testing_data\\Liang\\data_5_Liang_v7.csv',
    'Testing_data\\Liang\\data_6_Liang_v7.csv', 'Testing_data\\Liang\\data_7_Liang_v7.csv',
    'Testing_data\\Liang\\data_8_Liang_v7.csv',
    'Testing_data\\Liang\\data_9_Liang_v7.csv',
    'Testing_data\\shixun\\data_0_shiXun_v7.csv', 'Testing_data\\shixun\\data_1_shiXun_v7.csv',
    'Testing_data\\shixun\\data_2_shiXun_v7.csv',
    'Testing_data\\shixun\\data_3_shiXun_v7.csv', 'Testing_data\\shixun\\data_4_shiXun_v7.csv',
    'Testing_data\\shixun\\data_5_shiXun_v7.csv',
    'Testing_data\\shixun\\data_6_shiXun_v7.csv', 'Testing_data\\shixun\\data_7_shiXun_v7.csv',
    'Testing_data\\shixun\\data_8_shiXun_v7.csv',
    'Testing_data\\shixun\\data_9_shiXun_v7.csv'
]

label_filenames = ['Training_data\\0\\data_0_22_v7.csv_label_v1.txt', 'Training_data\\0\\data_0_22_2_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_011_021_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_120_122_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_021_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_120_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_122_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_021_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_22_v7.csv_label_v1.txt', 'Training_data\\2\\data_2_22_2_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_222_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_22_v7.csv_label_v1.txt', 'Training_data\\3\\data_3_22_2_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_220_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_v7.csv_label_v1.txt', 'Training_data\\4\\data_4_221_2_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_211_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_210_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_210_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_220_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_v7.csv_label_v1.txt', 'Training_data\\5\\data_5_221_2_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_121_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_220_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_121_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_221_220_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_v7.csv_label_v1.txt', 'Training_data\\7\\data_7_221_3_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_2_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s3_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s3_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_v7.csv_label_v1.txt', 'Training_data\\8\\data_8_221_3_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t4_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t5_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t4_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_120_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_220_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_220_3_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_120_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_s1_t1_1_v7.csv_label_v1.txt',

                   'Testing_data\\jundaWu\\data_0_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_1_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_2_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_3_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_4_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_5_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_6_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_7_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_8_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_9_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_0_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_1_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_2_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_3_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_4_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_5_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_6_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_7_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_8_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_9_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_0_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_1_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_2_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_3_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_4_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_5_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_6_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_7_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_8_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_9_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_0_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_1_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_2_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_3_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_4_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_5_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_6_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_7_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_8_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_9_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_0_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_1_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_2_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_3_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_4_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_5_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_6_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_7_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_8_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_9_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_0_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_1_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_2_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_3_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_4_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_5_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_6_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_7_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_8_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_9_shiXun_v7.csv_label_v1.txt'

                   ]

data_test_filenames_new = [
    'Testing_data\\HaozheTang\\data_0_HaozheTang_v7.csv', 'Testing_data\\HaozheTang\\data_1_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_2_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_3_HaozheTang_v7.csv', 'Testing_data\\HaozheTang\\data_4_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_5_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_6_HaozheTang_v7.csv', 'Testing_data\\HaozheTang\\data_7_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_8_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_9_HaozheTang_v7.csv',
    'Testing_data\\Qing2\\data_0_Qing2_v7.csv', 'Testing_data\\Qing\\data_1_Qing_v7.csv',
    'Testing_data\\Qing\\data_2_Qing_v7.csv',
    'Testing_data\\Qing\\data_3_Qing_v7.csv', 'Testing_data\\Qing\\data_4_Qing_v7.csv',
    'Testing_data\\Qing\\data_5_Qing_v7.csv',
    'Testing_data\\Qing\\data_6_Qing_v7.csv', 'Testing_data\\Qing\\data_7_Qing_v7.csv',
    'Testing_data\\Qing\\data_8_Qing_v7.csv',
    'Testing_data\\Qing\\data_9_Qing_v7.csv',
    'Testing_data\\Serge\\data_0_Serge_v7.csv', 'Testing_data\\Serge\\data_1_Serge_v7.csv',
    'Testing_data\\Serge\\data_2_Serge_v7.csv',
    'Testing_data\\Serge\\data_3_Serge_v7.csv', 'Testing_data\\Serge\\data_4_Serge_v7.csv',
    'Testing_data\\Serge\\data_5_Serge_v7.csv',
    'Testing_data\\Serge\\data_6_Serge_v7.csv', 'Testing_data\\Serge\\data_7_Serge_v7.csv',
    'Testing_data\\Serge\\data_8_Serge_v7.csv',
    'Testing_data\\Serge\\data_9_Serge_v7.csv',
    'Testing_data\\AlexCui\\data_0_AlexCui_v7.csv', 'Testing_data\\AlexCui\\data_1_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_2_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_3_AlexCui_v7.csv', 'Testing_data\\AlexCui\\data_4_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_5_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_6_AlexCui_v7.csv', 'Testing_data\\AlexCui\\data_7_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_8_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_9_AlexCui_v7.csv',
    'Testing_data\\Keyarash\\data_0_Keyarash_v7.csv', 'Testing_data\\Keyarash\\data_1_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_2_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_3_Keyarash_v7.csv', 'Testing_data\\Keyarash\\data_4_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_5_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_6_Keyarash_v7.csv', 'Testing_data\\Keyarash\\data_7_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_8_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_9_Keyarash_v7.csv',
    'Testing_data\\PingweiJiao\\data_0_PingweiJiao_v7.csv', 'Testing_data\\PingweiJiao\\data_1_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_2_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_3_PingweiJiao_v7.csv', 'Testing_data\\PingweiJiao\\data_4_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_5_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_6_PingweiJiao_v7.csv', 'Testing_data\\PingweiJiao\\data_7_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_8_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_9_PingweiJiao_v7.csv',
    'Testing_data\\Talia\\data_0_Talia_v7.csv', 'Testing_data\\Talia\\data_1_Talia_v7.csv',
    'Testing_data\\Talia\\data_2_Talia_v7.csv',
    'Testing_data\\Talia\\data_3_Talia_v7.csv', 'Testing_data\\Talia\\data_4_Talia_v7.csv',
    'Testing_data\\Talia\\data_5_Talia_v7.csv',
    'Testing_data\\Talia\\data_6_Talia_v7.csv', 'Testing_data\\Talia\\data_7_Talia_v7.csv',
    'Testing_data\\Talia\\data_8_Talia_v7.csv',
    'Testing_data\\Talia\\data_9_Talia_v7.csv',
    'Testing_data\\Vineet\\data_0_Vineet_v7.csv', 'Testing_data\\Vineet\\data_1_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_2_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_3_Vineet_v7.csv', 'Testing_data\\Vineet\\data_4_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_5_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_6_Vineet_v7.csv', 'Testing_data\\Vineet\\data_7_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_8_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_9_Vineet_v7.csv',
    'Testing_data\\Song\\data_0_Song_v7.csv', 'Testing_data\\Song\\data_1_Song_v7.csv',
    'Testing_data\\Song\\data_2_Song_v7.csv',
    'Testing_data\\Song\\data_3_Song_v7.csv', 'Testing_data\\Song\\data_4_Song_v7.csv',
    'Testing_data\\Song\\data_5_Song_v7.csv',
    'Testing_data\\Song\\data_6_Song_v7.csv', 'Testing_data\\Song\\data_7_Song_v7.csv',
    'Testing_data\\Song\\data_8_Song_v7.csv',
    'Testing_data\\Song\\data_9_Song_v7.csv',
    'Testing_data\\Vito\\data_0_Vito_v7.csv', 'Testing_data\\Vito\\data_1_Vito_v7.csv',
    'Testing_data\\Vito\\data_2_Vito_v7.csv',
    'Testing_data\\Vito\\data_3_Vito_v7.csv', 'Testing_data\\Vito\\data_4_Vito_v7.csv',
    'Testing_data\\Vito\\data_5_Vito_v7.csv',
    'Testing_data\\Vito\\data_6_Vito_v7.csv', 'Testing_data\\Vito\\data_7_Vito_v7.csv',
    'Testing_data\\Vito\\data_8_Vito_v7.csv',
    'Testing_data\\Vito\\data_9_Vito_v7.csv',
    'Testing_data\\YangLi\\data_0_YangLi_v7.csv', 'Testing_data\\YangLi\\data_1_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_2_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_3_YangLi_v7.csv', 'Testing_data\\YangLi\\data_4_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_5_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_6_YangLi_v7.csv', 'Testing_data\\YangLi\\data_7_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_8_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_9_YangLi_v7.csv',
    'Testing_data\\HanTing2\\data_0_HanTing2_v7.csv', 'Testing_data\\HanTing3\\data_1_HanTing3_v7.csv',
    'Testing_data\\HanTing2\\data_2_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_3_HanTing2_v7.csv', 'Testing_data\\HanTing2\\data_4_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_5_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_6_HanTing2_v7.csv', 'Testing_data\\HanTing3\\data_7_HanTing3_v7.csv',
    'Testing_data\\HanTing2\\data_8_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_9_HanTing2_v7.csv',
    'Testing_data\\Naram\\data_0_Naram_v7.csv', 'Testing_data\\Naram\\data_1_Naram_v7.csv',
    'Testing_data\\Naram\\data_2_Naram_v7.csv',
    'Testing_data\\Naram\\data_3_Naram_v7.csv', 'Testing_data\\Naram\\data_4_Naram_v7.csv',
    'Testing_data\\Naram\\data_5_Naram_v7.csv',
    'Testing_data\\Naram\\data_6_Naram_v7.csv', 'Testing_data\\Naram\\data_7_Naram_v7.csv',
    'Testing_data\\Naram\\data_8_Naram_v7.csv',
    'Testing_data\\Naram\\data_9_Naram_v7.csv',
    'Testing_data\\Ricardo\\data_0_Ricardo_v7.csv', 'Testing_data\\Ricardo\\data_1_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_2_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_3_Ricardo_v7.csv', 'Testing_data\\Ricardo\\data_4_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_5_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_6_Ricardo_v7.csv', 'Testing_data\\Ricardo\\data_7_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_8_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_9_Ricardo_v7.csv',
    'Testing_data\\Weichuan\\data_0_Weichuan_v7.csv', 'Testing_data\\Weichuan\\data_1_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_2_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_3_Weichuan_v7.csv', 'Testing_data\\Weichuan\\data_4_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_5_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_6_Weichuan_v7.csv', 'Testing_data\\Weichuan\\data_7_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_8_Weichuan_v7.csv',
]

label_test_filenames_new = [
    'Testing_data\\HaozheTang\\data_0_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_1_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_2_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_3_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_4_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_5_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_6_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_7_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_8_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\HaozheTang\\data_9_HaozheTang_v7.csv_label_v1.txt',
    'Testing_data\\Qing2\\data_0_Qing2_v7.csv_label_v1.txt', 'Testing_data\\Qing\\data_1_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Qing\\data_2_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Qing\\data_3_Qing_v7.csv_label_v1.txt', 'Testing_data\\Qing\\data_4_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Qing\\data_5_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Qing\\data_6_Qing_v7.csv_label_v1.txt', 'Testing_data\\Qing\\data_7_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Qing\\data_8_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Qing\\data_9_Qing_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_0_Serge_v7.csv_label_v1.txt', 'Testing_data\\Serge\\data_1_Serge_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_2_Serge_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_3_Serge_v7.csv_label_v1.txt', 'Testing_data\\Serge\\data_4_Serge_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_5_Serge_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_6_Serge_v7.csv_label_v1.txt', 'Testing_data\\Serge\\data_7_Serge_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_8_Serge_v7.csv_label_v1.txt',
    'Testing_data\\Serge\\data_9_Serge_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_0_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_1_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_2_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_3_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_4_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_5_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_6_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_7_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_8_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\AlexCui\\data_9_AlexCui_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_0_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_1_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_2_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_3_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_4_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_5_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_6_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_7_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_8_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\Keyarash\\data_9_Keyarash_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_0_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_1_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_2_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_3_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_4_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_5_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_6_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_7_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_8_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\PingweiJiao\\data_9_PingweiJiao_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_0_Talia_v7.csv_label_v1.txt', 'Testing_data\\Talia\\data_1_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_2_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_3_Talia_v7.csv_label_v1.txt', 'Testing_data\\Talia\\data_4_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_5_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_6_Talia_v7.csv_label_v1.txt', 'Testing_data\\Talia\\data_7_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_8_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Talia\\data_9_Talia_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_0_Vineet_v7.csv_label_v1.txt', 'Testing_data\\Vineet\\data_1_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_2_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_3_Vineet_v7.csv_label_v1.txt', 'Testing_data\\Vineet\\data_4_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_5_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_6_Vineet_v7.csv_label_v1.txt', 'Testing_data\\Vineet\\data_7_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_8_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Vineet\\data_9_Vineet_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_0_Song_v7.csv_label_v1.txt', 'Testing_data\\Song\\data_1_Song_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_2_Song_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_3_Song_v7.csv_label_v1.txt', 'Testing_data\\Song\\data_4_Song_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_5_Song_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_6_Song_v7.csv_label_v1.txt', 'Testing_data\\Song\\data_7_Song_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_8_Song_v7.csv_label_v1.txt',
    'Testing_data\\Song\\data_9_Song_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_0_Vito_v7.csv_label_v1.txt', 'Testing_data\\Vito\\data_1_Vito_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_2_Vito_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_3_Vito_v7.csv_label_v1.txt', 'Testing_data\\Vito\\data_4_Vito_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_5_Vito_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_6_Vito_v7.csv_label_v1.txt', 'Testing_data\\Vito\\data_7_Vito_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_8_Vito_v7.csv_label_v1.txt',
    'Testing_data\\Vito\\data_9_Vito_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_0_YangLi_v7.csv_label_v1.txt', 'Testing_data\\YangLi\\data_1_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_2_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_3_YangLi_v7.csv_label_v1.txt', 'Testing_data\\YangLi\\data_4_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_5_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_6_YangLi_v7.csv_label_v1.txt', 'Testing_data\\YangLi\\data_7_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_8_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\YangLi\\data_9_YangLi_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_0_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing3\\data_1_HanTing3_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_2_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_3_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_4_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_5_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_6_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing3\\data_7_HanTing3_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_8_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\HanTing2\\data_9_HanTing2_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_0_Naram_v7.csv_label_v1.txt', 'Testing_data\\Naram\\data_1_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_2_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_3_Naram_v7.csv_label_v1.txt', 'Testing_data\\Naram\\data_4_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_5_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_6_Naram_v7.csv_label_v1.txt', 'Testing_data\\Naram\\data_7_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_8_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Naram\\data_9_Naram_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_0_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_1_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_2_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_3_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_4_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_5_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_6_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_7_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_8_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Ricardo\\data_9_Ricardo_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_0_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_1_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_2_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_3_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_4_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_5_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_6_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_7_Weichuan_v7.csv_label_v1.txt',
    'Testing_data\\Weichuan\\data_8_Weichuan_v7.csv_label_v1.txt',

]
'''

data_filenames = [
    'Training_data\\0\\data_0_22_v7.csv', 'Training_data\\0\\data_0_22_2_v7.csv',
    'Training_data\\0\\data_0_121_s1_t1_1_v7.csv', 'Training_data\\0\\data_0_211_s1_t1_1_v7.csv',
    'Training_data\\0\\data_0_220_s1_t1_1_v7.csv', 'Training_data\\0\\data_0_221_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_011_021_v7.csv', 'Training_data\\1\\data_1_120_122_v7.csv',
    'Training_data\\1\\data_1_021_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_120_s1_t1_1_v7.csv', 'Training_data\\1\\data_1_122_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_021_s2_t1_1_v7.csv',
    'Training_data\\2\\data_2_22_v7.csv', 'Training_data\\2\\data_2_22_2_v7.csv',
    'Training_data\\2\\data_2_121_s1_t1_1_v7.csv', 'Training_data\\2\\data_2_211_s1_t1_1_v7.csv',
    'Training_data\\2\\data_2_220_s1_t1_1_v7.csv', 'Training_data\\2\\data_2_221_s1_t1_1_v7.csv',
    'Training_data\\2\\data_2_222_s1_t1_1_v7.csv',
    'Training_data\\3\\data_3_22_v7.csv', 'Training_data\\3\\data_3_22_2_v7.csv',
    'Training_data\\3\\data_3_121_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_121_s2_t1_1_v7.csv',
    'Training_data\\3\\data_3_220_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_220_s2_t1_1_v7.csv',
    'Training_data\\3\\data_3_221_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_221_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_221_v7.csv', 'Training_data\\4\\data_4_221_2_v7.csv',
    'Training_data\\4\\data_4_121_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_121_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_211_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_211_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_210_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_210_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_220_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_220_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_221_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_221_s2_t1_1_v7.csv',
    'Training_data\\5\\data_5_221_v7.csv', 'Training_data\\5\\data_5_221_2_v7.csv',
    'Training_data\\5\\data_5_121_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_121_s1_t2_1_v7.csv',
    'Training_data\\5\\data_5_220_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_220_s1_t2_1_v7.csv',
    'Training_data\\5\\data_5_221_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_221_s1_t2_1_v7.csv',
    'Training_data\\6\\data_6_121_v7.csv', 'Training_data\\6\\data_6_221_220_v7.csv',
    'Training_data\\6\\data_6_121_s1_t1_1_v7.csv', 'Training_data\\6\\data_6_221_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_v7.csv', 'Training_data\\7\\data_7_221_3_v7.csv', 'Training_data\\7\\data_7_221_2_v7.csv',
    'Training_data\\7\\data_7_121_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_121_s2_t1_1_v7.csv', 'Training_data\\7\\data_7_121_s3_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_s2_t1_1_v7.csv', 'Training_data\\7\\data_7_221_s3_t1_1_v7.csv',
    'Training_data\\8\\data_8_221_v7.csv', 'Training_data\\8\\data_8_221_3_v7.csv',
    'Training_data\\8\\data_8_121_s1_t1_1_v7.csv', 'Training_data\\8\\data_8_121_s1_t2_1_v7.csv',
    'Training_data\\8\\data_8_121_s1_t3_1_v7.csv', 'Training_data\\8\\data_8_220_s1_t1_1_v7.csv',
    'Training_data\\8\\data_8_220_s1_t2_1_v7.csv', 'Training_data\\8\\data_8_220_s1_t3_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t1_1_v7.csv', 'Training_data\\8\\data_8_221_s1_t2_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t3_1_v7.csv', 'Training_data\\8\\data_8_221_s1_t4_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t5_1_v7.csv', 'Training_data\\8\\data_8_121_s1_t4_1_v7.csv',
    'Training_data\\9\\data_9_120_v7.csv', 'Training_data\\9\\data_9_221_220_v7.csv',
    'Training_data\\9\\data_9_221_220_3_v7.csv',
    'Training_data\\9\\data_9_120_s1_t1_1_v7.csv', 'Training_data\\9\\data_9_121_s1_t1_1_v7.csv',
    'Training_data\\9\\data_9_220_s1_t1_1_v7.csv', 'Training_data\\9\\data_9_221_s1_t1_1_v7.csv'
]

label_filenames = ['Training_data\\0\\data_0_22_v7.csv_label_v1.txt', 'Training_data\\0\\data_0_22_2_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_011_021_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_120_122_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_021_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_120_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_122_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_021_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_22_v7.csv_label_v1.txt', 'Training_data\\2\\data_2_22_2_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_222_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_22_v7.csv_label_v1.txt', 'Training_data\\3\\data_3_22_2_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_220_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_v7.csv_label_v1.txt', 'Training_data\\4\\data_4_221_2_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_211_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_210_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_210_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_220_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_v7.csv_label_v1.txt', 'Training_data\\5\\data_5_221_2_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_121_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_220_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_121_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_221_220_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_v7.csv_label_v1.txt', 'Training_data\\7\\data_7_221_3_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_2_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s3_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s3_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_v7.csv_label_v1.txt', 'Training_data\\8\\data_8_221_3_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t4_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t5_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t4_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_120_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_220_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_220_3_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_120_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_s1_t1_1_v7.csv_label_v1.txt'
                   ]

data_test_filenames_new = ['Testing_data\\jundaWu\\data_0_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_1_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_2_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_3_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_4_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_5_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_6_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_7_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_8_jundaWu_v7.csv',
                           'Testing_data\\jundaWu\\data_9_jundaWu_v7.csv',
                           'Testing_data\\xinyunXu\\data_0_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_1_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_2_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_3_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_4_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_5_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_6_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_7_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_8_XinyunXu_v7.csv',
                           'Testing_data\\xinyunXu\\data_9_XinyunXu_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_0_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_1_xie_3_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_2_xie_3_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_3_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_4_xie_3_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_5_xie_3_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_6_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_7_xie_3_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_8_xie_3_v7.csv',
                           'Testing_data\\yuanhaoXie\\data_9_xie_3_v7.csv',
                           'Testing_data\\zehangWu\\data_0_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_1_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_2_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_3_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_4_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_5_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_6_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_7_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_8_ZehangWu_v7.csv',
                           'Testing_data\\zehangWu\\data_9_ZehangWu_v7.csv',
                           'Testing_data\\Liang\\data_0_Liang_v7.csv', 'Testing_data\\Liang\\data_1_Liang_v7.csv',
                           'Testing_data\\Liang\\data_2_Liang_v7.csv',
                           'Testing_data\\Liang\\data_3_Liang_v7.csv', 'Testing_data\\Liang\\data_4_Liang_v7.csv',
                           'Testing_data\\Liang\\data_5_Liang_v7.csv',
                           'Testing_data\\Liang\\data_6_Liang_v7.csv', 'Testing_data\\Liang\\data_7_Liang_v7.csv',
                           'Testing_data\\Liang\\data_8_Liang_v7.csv',
                           'Testing_data\\Liang\\data_9_Liang_v7.csv',
                           'Testing_data\\shixun\\data_0_shiXun_v7.csv', 'Testing_data\\shixun\\data_1_shiXun_v7.csv',
                           'Testing_data\\shixun\\data_2_shiXun_v7.csv',
                           'Testing_data\\shixun\\data_3_shiXun_v7.csv', 'Testing_data\\shixun\\data_4_shiXun_v7.csv',
                           'Testing_data\\shixun\\data_5_shiXun_v7.csv',
                           'Testing_data\\shixun\\data_6_shiXun_v7.csv', 'Testing_data\\shixun\\data_7_shiXun_v7.csv',
                           'Testing_data\\shixun\\data_8_shiXun_v7.csv',
                           'Testing_data\\shixun\\data_9_shiXun_v7.csv']

label_test_filenames_new = [
    'Testing_data\\jundaWu\\data_0_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_1_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_2_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_3_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_4_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_5_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_6_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_7_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_8_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\jundaWu\\data_9_jundaWu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_0_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_1_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_2_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_3_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_4_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_5_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_6_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_7_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_8_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\xinyunXu\\data_9_XinyunXu_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_0_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_1_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_2_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_3_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_4_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_5_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_6_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_7_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_8_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\yuanhaoXie\\data_9_xie_3_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_0_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_1_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_2_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_3_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_4_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_5_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_6_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_7_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_8_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\zehangWu\\data_9_ZehangWu_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_0_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_1_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_2_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_3_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_4_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_5_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_6_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_7_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_8_Liang_v7.csv_label_v1.txt',
    'Testing_data\\Liang\\data_9_Liang_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_0_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_1_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_2_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_3_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_4_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_5_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_6_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_7_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_8_shiXun_v7.csv_label_v1.txt',
    'Testing_data\\shixun\\data_9_shiXun_v7.csv_label_v1.txt'
]

'''
data_filenames = [
    'Training_data\\0\\data_0_22_v7.csv', 'Training_data\\0\\data_0_22_2_v7.csv',
    'Training_data\\0\\data_0_121_s1_t1_1_v7.csv', 'Training_data\\0\\data_0_211_s1_t1_1_v7.csv',
    'Training_data\\0\\data_0_220_s1_t1_1_v7.csv', 'Training_data\\0\\data_0_221_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_011_021_v7.csv', 'Training_data\\1\\data_1_120_122_v7.csv',
    'Training_data\\1\\data_1_021_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_120_s1_t1_1_v7.csv', 'Training_data\\1\\data_1_122_s1_t1_1_v7.csv',
    'Training_data\\1\\data_1_021_s2_t1_1_v7.csv',
    'Training_data\\2\\data_2_22_v7.csv', 'Training_data\\2\\data_2_22_2_v7.csv',
    'Training_data\\2\\data_2_121_s1_t1_1_v7.csv', 'Training_data\\2\\data_2_211_s1_t1_1_v7.csv',
    'Training_data\\2\\data_2_220_s1_t1_1_v7.csv', 'Training_data\\2\\data_2_221_s1_t1_1_v7.csv',
    'Training_data\\2\\data_2_222_s1_t1_1_v7.csv',
    'Training_data\\3\\data_3_22_v7.csv', 'Training_data\\3\\data_3_22_2_v7.csv',
    'Training_data\\3\\data_3_121_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_121_s2_t1_1_v7.csv',
    'Training_data\\3\\data_3_220_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_220_s2_t1_1_v7.csv',
    'Training_data\\3\\data_3_221_s1_t1_1_v7.csv', 'Training_data\\3\\data_3_221_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_221_v7.csv', 'Training_data\\4\\data_4_221_2_v7.csv',
    'Training_data\\4\\data_4_121_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_121_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_211_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_211_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_210_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_210_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_220_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_220_s2_t1_1_v7.csv',
    'Training_data\\4\\data_4_221_s1_t1_1_v7.csv', 'Training_data\\4\\data_4_221_s2_t1_1_v7.csv',
    'Training_data\\5\\data_5_221_v7.csv', 'Training_data\\5\\data_5_221_2_v7.csv',
    'Training_data\\5\\data_5_121_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_121_s1_t2_1_v7.csv',
    'Training_data\\5\\data_5_220_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_220_s1_t2_1_v7.csv',
    'Training_data\\5\\data_5_221_s1_t1_1_v7.csv', 'Training_data\\5\\data_5_221_s1_t2_1_v7.csv',
    'Training_data\\6\\data_6_121_v7.csv', 'Training_data\\6\\data_6_221_220_v7.csv',
    'Training_data\\6\\data_6_121_s1_t1_1_v7.csv', 'Training_data\\6\\data_6_221_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_v7.csv', 'Training_data\\7\\data_7_221_3_v7.csv', 'Training_data\\7\\data_7_221_2_v7.csv',
    'Training_data\\7\\data_7_121_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_121_s2_t1_1_v7.csv', 'Training_data\\7\\data_7_121_s3_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_s1_t1_1_v7.csv',
    'Training_data\\7\\data_7_221_s2_t1_1_v7.csv', 'Training_data\\7\\data_7_221_s3_t1_1_v7.csv',
    'Training_data\\8\\data_8_221_v7.csv', 'Training_data\\8\\data_8_221_3_v7.csv',
    'Training_data\\8\\data_8_121_s1_t1_1_v7.csv', 'Training_data\\8\\data_8_121_s1_t2_1_v7.csv',
    'Training_data\\8\\data_8_121_s1_t3_1_v7.csv', 'Training_data\\8\\data_8_220_s1_t1_1_v7.csv',
    'Training_data\\8\\data_8_220_s1_t2_1_v7.csv', 'Training_data\\8\\data_8_220_s1_t3_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t1_1_v7.csv', 'Training_data\\8\\data_8_221_s1_t2_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t3_1_v7.csv', 'Training_data\\8\\data_8_221_s1_t4_1_v7.csv',
    'Training_data\\8\\data_8_221_s1_t5_1_v7.csv', 'Training_data\\8\\data_8_121_s1_t4_1_v7.csv',
    'Training_data\\9\\data_9_120_v7.csv', 'Training_data\\9\\data_9_221_220_v7.csv',
    'Training_data\\9\\data_9_221_220_3_v7.csv',
    'Training_data\\9\\data_9_120_s1_t1_1_v7.csv', 'Training_data\\9\\data_9_121_s1_t1_1_v7.csv',
    'Training_data\\9\\data_9_220_s1_t1_1_v7.csv', 'Training_data\\9\\data_9_221_s1_t1_1_v7.csv',

    'Testing_data\\jundaWu\\data_0_jundaWu_v7.csv', 'Testing_data\\jundaWu\\data_1_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_2_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_3_jundaWu_v7.csv', 'Testing_data\\jundaWu\\data_4_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_5_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_6_jundaWu_v7.csv', 'Testing_data\\jundaWu\\data_7_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_8_jundaWu_v7.csv',
    'Testing_data\\jundaWu\\data_9_jundaWu_v7.csv',
    'Testing_data\\xinyunXu\\data_0_XinyunXu_v7.csv', 'Testing_data\\xinyunXu\\data_1_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_2_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_3_XinyunXu_v7.csv', 'Testing_data\\xinyunXu\\data_4_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_5_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_6_XinyunXu_v7.csv', 'Testing_data\\xinyunXu\\data_7_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_8_XinyunXu_v7.csv',
    'Testing_data\\xinyunXu\\data_9_XinyunXu_v7.csv',
    'Testing_data\\yuanhaoXie\\data_0_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_1_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_2_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_3_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_4_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_5_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_6_xie_3_v7.csv', 'Testing_data\\yuanhaoXie\\data_7_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_8_xie_3_v7.csv',
    'Testing_data\\yuanhaoXie\\data_9_xie_3_v7.csv',
    'Testing_data\\zehangWu\\data_0_ZehangWu_v7.csv', 'Testing_data\\zehangWu\\data_1_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_2_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_3_ZehangWu_v7.csv', 'Testing_data\\zehangWu\\data_4_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_5_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_6_ZehangWu_v7.csv', 'Testing_data\\zehangWu\\data_7_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_8_ZehangWu_v7.csv',
    'Testing_data\\zehangWu\\data_9_ZehangWu_v7.csv',
    'Testing_data\\Liang\\data_0_Liang_v7.csv', 'Testing_data\\Liang\\data_1_Liang_v7.csv',
    'Testing_data\\Liang\\data_2_Liang_v7.csv',
    'Testing_data\\Liang\\data_3_Liang_v7.csv', 'Testing_data\\Liang\\data_4_Liang_v7.csv',
    'Testing_data\\Liang\\data_5_Liang_v7.csv',
    'Testing_data\\Liang\\data_6_Liang_v7.csv', 'Testing_data\\Liang\\data_7_Liang_v7.csv',
    'Testing_data\\Liang\\data_8_Liang_v7.csv',
    'Testing_data\\Liang\\data_9_Liang_v7.csv',
    'Testing_data\\shixun\\data_0_shiXun_v7.csv', 'Testing_data\\shixun\\data_1_shiXun_v7.csv',
    'Testing_data\\shixun\\data_2_shiXun_v7.csv',
    'Testing_data\\shixun\\data_3_shiXun_v7.csv', 'Testing_data\\shixun\\data_4_shiXun_v7.csv',
    'Testing_data\\shixun\\data_5_shiXun_v7.csv',
    'Testing_data\\shixun\\data_6_shiXun_v7.csv', 'Testing_data\\shixun\\data_7_shiXun_v7.csv',
    'Testing_data\\shixun\\data_8_shiXun_v7.csv',
    'Testing_data\\shixun\\data_9_shiXun_v7.csv',

    'Testing_data\\HaozheTang\\data_0_HaozheTang_v7.csv', 'Testing_data\\HaozheTang\\data_1_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_2_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_3_HaozheTang_v7.csv', 'Testing_data\\HaozheTang\\data_4_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_5_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_6_HaozheTang_v7.csv', 'Testing_data\\HaozheTang\\data_7_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_8_HaozheTang_v7.csv',
    'Testing_data\\HaozheTang\\data_9_HaozheTang_v7.csv',
    'Testing_data\\Qing2\\data_0_Qing2_v7.csv', 'Testing_data\\Qing\\data_1_Qing_v7.csv',
    'Testing_data\\Qing\\data_2_Qing_v7.csv',
    'Testing_data\\Qing\\data_3_Qing_v7.csv', 'Testing_data\\Qing\\data_4_Qing_v7.csv',
    'Testing_data\\Qing\\data_5_Qing_v7.csv',
    'Testing_data\\Qing\\data_6_Qing_v7.csv', 'Testing_data\\Qing\\data_7_Qing_v7.csv',
    'Testing_data\\Qing\\data_8_Qing_v7.csv',
    'Testing_data\\Qing\\data_9_Qing_v7.csv',
    'Testing_data\\Serge\\data_0_Serge_v7.csv', 'Testing_data\\Serge\\data_1_Serge_v7.csv',
    'Testing_data\\Serge\\data_2_Serge_v7.csv',
    'Testing_data\\Serge\\data_3_Serge_v7.csv', 'Testing_data\\Serge\\data_4_Serge_v7.csv',
    'Testing_data\\Serge\\data_5_Serge_v7.csv',
    'Testing_data\\Serge\\data_6_Serge_v7.csv', 'Testing_data\\Serge\\data_7_Serge_v7.csv',
    'Testing_data\\Serge\\data_8_Serge_v7.csv',
    'Testing_data\\Serge\\data_9_Serge_v7.csv',
    'Testing_data\\AlexCui\\data_0_AlexCui_v7.csv', 'Testing_data\\AlexCui\\data_1_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_2_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_3_AlexCui_v7.csv', 'Testing_data\\AlexCui\\data_4_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_5_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_6_AlexCui_v7.csv', 'Testing_data\\AlexCui\\data_7_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_8_AlexCui_v7.csv',
    'Testing_data\\AlexCui\\data_9_AlexCui_v7.csv',
    'Testing_data\\Keyarash\\data_0_Keyarash_v7.csv', 'Testing_data\\Keyarash\\data_1_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_2_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_3_Keyarash_v7.csv', 'Testing_data\\Keyarash\\data_4_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_5_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_6_Keyarash_v7.csv', 'Testing_data\\Keyarash\\data_7_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_8_Keyarash_v7.csv',
    'Testing_data\\Keyarash\\data_9_Keyarash_v7.csv',
    'Testing_data\\PingweiJiao\\data_0_PingweiJiao_v7.csv', 'Testing_data\\PingweiJiao\\data_1_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_2_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_3_PingweiJiao_v7.csv', 'Testing_data\\PingweiJiao\\data_4_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_5_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_6_PingweiJiao_v7.csv', 'Testing_data\\PingweiJiao\\data_7_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_8_PingweiJiao_v7.csv',
    'Testing_data\\PingweiJiao\\data_9_PingweiJiao_v7.csv',
    'Testing_data\\Talia\\data_0_Talia_v7.csv', 'Testing_data\\Talia\\data_1_Talia_v7.csv',
    'Testing_data\\Talia\\data_2_Talia_v7.csv',
    'Testing_data\\Talia\\data_3_Talia_v7.csv', 'Testing_data\\Talia\\data_4_Talia_v7.csv',
    'Testing_data\\Talia\\data_5_Talia_v7.csv',
    'Testing_data\\Talia\\data_6_Talia_v7.csv', 'Testing_data\\Talia\\data_7_Talia_v7.csv',
    'Testing_data\\Talia\\data_8_Talia_v7.csv',
    'Testing_data\\Talia\\data_9_Talia_v7.csv',
    'Testing_data\\Vineet\\data_0_Vineet_v7.csv', 'Testing_data\\Vineet\\data_1_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_2_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_3_Vineet_v7.csv', 'Testing_data\\Vineet\\data_4_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_5_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_6_Vineet_v7.csv', 'Testing_data\\Vineet\\data_7_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_8_Vineet_v7.csv',
    'Testing_data\\Vineet\\data_9_Vineet_v7.csv',
    'Testing_data\\Song\\data_0_Song_v7.csv', 'Testing_data\\Song\\data_1_Song_v7.csv',
    'Testing_data\\Song\\data_2_Song_v7.csv',
    'Testing_data\\Song\\data_3_Song_v7.csv', 'Testing_data\\Song\\data_4_Song_v7.csv',
    'Testing_data\\Song\\data_5_Song_v7.csv',
    'Testing_data\\Song\\data_6_Song_v7.csv', 'Testing_data\\Song\\data_7_Song_v7.csv',
    'Testing_data\\Song\\data_8_Song_v7.csv',
    'Testing_data\\Song\\data_9_Song_v7.csv',
    'Testing_data\\Vito\\data_0_Vito_v7.csv', 'Testing_data\\Vito\\data_1_Vito_v7.csv',
    'Testing_data\\Vito\\data_2_Vito_v7.csv',
    'Testing_data\\Vito\\data_3_Vito_v7.csv', 'Testing_data\\Vito\\data_4_Vito_v7.csv',
    'Testing_data\\Vito\\data_5_Vito_v7.csv',
    'Testing_data\\Vito\\data_6_Vito_v7.csv', 'Testing_data\\Vito\\data_7_Vito_v7.csv',
    'Testing_data\\Vito\\data_8_Vito_v7.csv',
    'Testing_data\\Vito\\data_9_Vito_v7.csv',
    'Testing_data\\YangLi\\data_0_YangLi_v7.csv', 'Testing_data\\YangLi\\data_1_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_2_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_3_YangLi_v7.csv', 'Testing_data\\YangLi\\data_4_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_5_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_6_YangLi_v7.csv', 'Testing_data\\YangLi\\data_7_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_8_YangLi_v7.csv',
    'Testing_data\\YangLi\\data_9_YangLi_v7.csv',
    'Testing_data\\HanTing2\\data_0_HanTing2_v7.csv', 'Testing_data\\HanTing3\\data_1_HanTing3_v7.csv',
    'Testing_data\\HanTing2\\data_2_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_3_HanTing2_v7.csv', 'Testing_data\\HanTing2\\data_4_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_5_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_6_HanTing2_v7.csv', 'Testing_data\\HanTing3\\data_7_HanTing3_v7.csv',
    'Testing_data\\HanTing2\\data_8_HanTing2_v7.csv',
    'Testing_data\\HanTing2\\data_9_HanTing2_v7.csv',
    'Testing_data\\Naram\\data_0_Naram_v7.csv', 'Testing_data\\Naram\\data_1_Naram_v7.csv',
    'Testing_data\\Naram\\data_2_Naram_v7.csv',
    'Testing_data\\Naram\\data_3_Naram_v7.csv', 'Testing_data\\Naram\\data_4_Naram_v7.csv',
    'Testing_data\\Naram\\data_5_Naram_v7.csv',
    'Testing_data\\Naram\\data_6_Naram_v7.csv', 'Testing_data\\Naram\\data_7_Naram_v7.csv',
    'Testing_data\\Naram\\data_8_Naram_v7.csv',
    'Testing_data\\Naram\\data_9_Naram_v7.csv',
    'Testing_data\\Ricardo\\data_0_Ricardo_v7.csv', 'Testing_data\\Ricardo\\data_1_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_2_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_3_Ricardo_v7.csv', 'Testing_data\\Ricardo\\data_4_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_5_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_6_Ricardo_v7.csv', 'Testing_data\\Ricardo\\data_7_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_8_Ricardo_v7.csv',
    'Testing_data\\Ricardo\\data_9_Ricardo_v7.csv',
    'Testing_data\\Weichuan\\data_0_Weichuan_v7.csv', 'Testing_data\\Weichuan\\data_1_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_2_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_3_Weichuan_v7.csv', 'Testing_data\\Weichuan\\data_4_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_5_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_6_Weichuan_v7.csv', 'Testing_data\\Weichuan\\data_7_Weichuan_v7.csv',
    'Testing_data\\Weichuan\\data_8_Weichuan_v7.csv',
]

label_filenames = ['Training_data\\0\\data_0_22_v7.csv_label_v1.txt', 'Training_data\\0\\data_0_22_2_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\0\\data_0_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_011_021_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_120_122_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_021_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_120_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_122_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\1\\data_1_021_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_22_v7.csv_label_v1.txt', 'Training_data\\2\\data_2_22_2_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\2\\data_2_222_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_22_v7.csv_label_v1.txt', 'Training_data\\3\\data_3_22_2_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_220_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\3\\data_3_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_v7.csv_label_v1.txt', 'Training_data\\4\\data_4_221_2_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_211_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_211_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_210_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_210_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_220_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\4\\data_4_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_v7.csv_label_v1.txt', 'Training_data\\5\\data_5_221_2_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_121_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_220_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\5\\data_5_221_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_121_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_221_220_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\6\\data_6_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_v7.csv_label_v1.txt', 'Training_data\\7\\data_7_221_3_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_2_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_121_s3_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s2_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\7\\data_7_221_s3_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_v7.csv_label_v1.txt', 'Training_data\\8\\data_8_221_3_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_220_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t2_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t3_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t4_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_221_s1_t5_1_v7.csv_label_v1.txt',
                   'Training_data\\8\\data_8_121_s1_t4_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_120_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_220_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_220_3_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_120_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_121_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_220_s1_t1_1_v7.csv_label_v1.txt',
                   'Training_data\\9\\data_9_221_s1_t1_1_v7.csv_label_v1.txt',

                   'Testing_data\\jundaWu\\data_0_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_1_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_2_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_3_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_4_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_5_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_6_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_7_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_8_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\jundaWu\\data_9_jundaWu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_0_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_1_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_2_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_3_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_4_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_5_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_6_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_7_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_8_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\xinyunXu\\data_9_XinyunXu_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_0_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_1_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_2_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_3_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_4_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_5_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_6_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_7_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_8_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\yuanhaoXie\\data_9_xie_3_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_0_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_1_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_2_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_3_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_4_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_5_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_6_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_7_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_8_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\zehangWu\\data_9_ZehangWu_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_0_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_1_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_2_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_3_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_4_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_5_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_6_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_7_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_8_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\Liang\\data_9_Liang_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_0_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_1_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_2_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_3_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_4_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_5_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_6_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_7_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_8_shiXun_v7.csv_label_v1.txt',
                   'Testing_data\\shixun\\data_9_shiXun_v7.csv_label_v1.txt',

                    'Testing_data\\HaozheTang\\data_0_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_1_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_2_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_3_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_4_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_5_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_6_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_7_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_8_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\HaozheTang\\data_9_HaozheTang_v7.csv_label_v1.txt',
                    'Testing_data\\Qing2\\data_0_Qing2_v7.csv_label_v1.txt', 'Testing_data\\Qing\\data_1_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Qing\\data_2_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Qing\\data_3_Qing_v7.csv_label_v1.txt', 'Testing_data\\Qing\\data_4_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Qing\\data_5_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Qing\\data_6_Qing_v7.csv_label_v1.txt', 'Testing_data\\Qing\\data_7_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Qing\\data_8_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Qing\\data_9_Qing_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_0_Serge_v7.csv_label_v1.txt', 'Testing_data\\Serge\\data_1_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_2_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_3_Serge_v7.csv_label_v1.txt', 'Testing_data\\Serge\\data_4_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_5_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_6_Serge_v7.csv_label_v1.txt', 'Testing_data\\Serge\\data_7_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_8_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\Serge\\data_9_Serge_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_0_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_1_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_2_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_3_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_4_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_5_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_6_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_7_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_8_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\AlexCui\\data_9_AlexCui_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_0_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_1_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_2_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_3_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_4_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_5_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_6_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_7_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_8_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\Keyarash\\data_9_Keyarash_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_0_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_1_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_2_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_3_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_4_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_5_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_6_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_7_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_8_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\PingweiJiao\\data_9_PingweiJiao_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_0_Talia_v7.csv_label_v1.txt', 'Testing_data\\Talia\\data_1_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_2_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_3_Talia_v7.csv_label_v1.txt', 'Testing_data\\Talia\\data_4_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_5_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_6_Talia_v7.csv_label_v1.txt', 'Testing_data\\Talia\\data_7_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_8_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Talia\\data_9_Talia_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_0_Vineet_v7.csv_label_v1.txt', 'Testing_data\\Vineet\\data_1_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_2_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_3_Vineet_v7.csv_label_v1.txt', 'Testing_data\\Vineet\\data_4_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_5_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_6_Vineet_v7.csv_label_v1.txt', 'Testing_data\\Vineet\\data_7_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_8_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Vineet\\data_9_Vineet_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_0_Song_v7.csv_label_v1.txt', 'Testing_data\\Song\\data_1_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_2_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_3_Song_v7.csv_label_v1.txt', 'Testing_data\\Song\\data_4_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_5_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_6_Song_v7.csv_label_v1.txt', 'Testing_data\\Song\\data_7_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_8_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Song\\data_9_Song_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_0_Vito_v7.csv_label_v1.txt', 'Testing_data\\Vito\\data_1_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_2_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_3_Vito_v7.csv_label_v1.txt', 'Testing_data\\Vito\\data_4_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_5_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_6_Vito_v7.csv_label_v1.txt', 'Testing_data\\Vito\\data_7_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_8_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\Vito\\data_9_Vito_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_0_YangLi_v7.csv_label_v1.txt', 'Testing_data\\YangLi\\data_1_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_2_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_3_YangLi_v7.csv_label_v1.txt', 'Testing_data\\YangLi\\data_4_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_5_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_6_YangLi_v7.csv_label_v1.txt', 'Testing_data\\YangLi\\data_7_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_8_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\YangLi\\data_9_YangLi_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_0_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing3\\data_1_HanTing3_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_2_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_3_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_4_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_5_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_6_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing3\\data_7_HanTing3_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_8_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\HanTing2\\data_9_HanTing2_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_0_Naram_v7.csv_label_v1.txt', 'Testing_data\\Naram\\data_1_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_2_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_3_Naram_v7.csv_label_v1.txt', 'Testing_data\\Naram\\data_4_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_5_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_6_Naram_v7.csv_label_v1.txt', 'Testing_data\\Naram\\data_7_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_8_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Naram\\data_9_Naram_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_0_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_1_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_2_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_3_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_4_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_5_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_6_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_7_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_8_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Ricardo\\data_9_Ricardo_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_0_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_1_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_2_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_3_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_4_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_5_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_6_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_7_Weichuan_v7.csv_label_v1.txt',
                    'Testing_data\\Weichuan\\data_8_Weichuan_v7.csv_label_v1.txt',

]
'''

learning_rate = [0.001]
verbose, epochs = 0, 20
Batch_size = [32]

n_steps, n_length = 60, 5
num_filters = [32]
num_kernels = [3]
num_lstm_Neurons = [1024]
num_heads = [2]
num_fcn_Neurons = [1024]
Attention_Neurons = [1]


def create_label_frame(file_name):
    label_frame = pd.DataFrame(columns=['label'])
    for i, file in enumerate(file_name):
        data = pd.read_csv("C:\\Users\\Razer\\LightDigitDataset\\Blocked Dataset\\Dataset\\" + file, names=['label'])
        label_frame = pd.concat([label_frame, data], axis=0, ignore_index=True)
    return label_frame


def create_data_frame(file_name):
    data_frame = []
    for i, file in enumerate(file_name):
        data = pd.read_csv("C:\\Users\\Razer\\LightDigitDataset\\Blocked Dataset\\Dataset\\" + file)
        data_frame.append(data)
    data_frame = pd.concat(data_frame, join='outer')
    return data_frame


def data_3D_transfer(photodiode_arr, data_frame):
    data_3D = list()
    for i, photodiode_name in enumerate(photodiode_arr):
        data_3D.append(data_frame[photodiode_name].values.reshape(-1, ))
    data_3D = dstack(data_3D)
    data_3D = data_3D.reshape((-1, 300, 9))
    return data_3D


def load_dataset():
    photodiode_arr = ['6', '1', '2', '3', '9', '8', '7', '4', '5']
    label_frame = create_label_frame(label_filenames)
    label_test_frame_new = create_label_frame(label_test_filenames_new)
    data_frame = create_data_frame(data_filenames)
    data_test_frame_new = create_data_frame(data_test_filenames_new)
    data_3D = data_3D_transfer(photodiode_arr, data_frame)
    data_test_3D_new = data_3D_transfer(photodiode_arr, data_test_frame_new)
    data_y = label_frame
    data_test_y_new = label_test_frame_new
    data_y = to_categorical(data_y, num_classes=10)
    print(data_y)
    print('data_y : ', len(data_y))
    print('data_test_y : ', len(data_test_y_new))
    data_test_y_new = to_categorical(data_test_y_new, num_classes=10)
    Xtra, Xval, Ytra, Yval = train_test_split(data_3D, data_y, test_size=0.2, shuffle=True)
    return Xtra, Ytra, Xval, Yval, data_test_3D_new, data_test_y_new


'''

def load_dataset():
    photodiode_arr = ['6', '1', '2', '3', '9', '8', '7', '4', '5']
    label_frame = create_label_frame(label_filenames)
    data_frame = create_data_frame(data_filenames)
    data_3D = data_3D_transfer(photodiode_arr, data_frame)
    data_y = label_frame
    data_y = to_categorical(data_y, num_classes=10)
    print('data_y : ', len(data_y))
    X_tra, X_test, y_tra, y_test = train_test_split(data_3D, data_y, test_size=0.2, shuffle=True)
    X_train, X_val, y_train, y_val = train_test_split(X_tra, y_tra, test_size=0.25, shuffle=True)
    return X_train, y_train, X_val, y_val, X_test, y_test
'''


def pre_processing():
    trainX, trainy, valX, valy, tstX_new, tsty_new = load_dataset()
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    trainX1 = trainX.reshape((trainX.shape[0], n_steps, n_length, n_features))
    valX1 = valX.reshape((valX.shape[0], n_steps, n_length, n_features))
    tstX_new1 = tstX_new.reshape((tstX_new.shape[0], n_steps, n_length, n_features))
    return trainX1, trainy, valX1, valy, tstX_new1, tsty_new


if __name__ == '__main__':
    X_train, y_train, X_val, y_val, X_test, y_test = load_dataset()
    # print(X_train)
    # print(X_train.shape)
    # print(y_train.shape)
    # print(X_val.shape)
    # print(y_val.shape)
    # print(X_test.shape)
    # print(y_test.shape)
